#!/usr/bin/env python3

# TODO: question selection
# TODO: grammar
# TODO: choose correct wh-word
# TODO: prune auxiliary clauses
# TODO: Possibly generate better questions by looking for more specific things?
# TODO: Yes/no questions

from random import sample

answers = """I don't know
I need to look this up
who knows
google it
1973
i was born in India
selemat pagi
satu dua tiga""".split("\n")

def rand():
    return sample(answers,1)[0]

import sys

_, article_path, questions_path, *__ = sys.argv

with open(questions_path) as f:
    for line in f:
        print(rand())
